/* ============================================================
   PRÜFUNGEN (Inhalt)
   ============================================================ */
exam({id:"m1",title:"B1 Modelltest 1",sub:"Kompletter Test: Lesen · Hören · Schreiben · Sprechen. Format Zertifikat B1.",sections:[
 {type:"lesen",title:"Lesen · Teil 1",instr:"Lesen Sie die E-Mail. Sind die Aussagen *richtig* oder *falsch*?",
  text:"*Liebe Sofia,*\n\nendlich habe ich Zeit, dir zu schreiben! Letzte Woche war ich mit meiner Familie im Urlaub in Österreich. Wir sind mit dem Zug gefahren, weil Fliegen zu teuer war. Das Wetter war leider nicht so gut — es hat oft geregnet. Trotzdem haben wir viel gemacht: Wir waren wandern, haben eine alte Burg besichtigt und jeden Abend gemütlich gekocht. Am liebsten mochte ich den großen See; dort konnte man sogar schwimmen, obwohl das Wasser sehr kalt war. Nächstes Jahr wollen wir wieder hinfahren, aber im Sommer. Wie war eigentlich dein Urlaub? Schreib mir bald!\n\nLiebe Grüße, Mia",
  items:[
   {q:"Mia war allein im Urlaub.",options:["Richtig","Falsch"],answer:"Falsch",explain:"Sie war 'mit meiner Familie' im Urlaub."},
   {q:"Die Familie ist mit dem Zug gereist.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Wir sind mit dem Zug gefahren, weil Fliegen zu teuer war.'"},
   {q:"Das Wetter war die ganze Zeit schön.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Das Wetter war leider nicht so gut — es hat oft geregnet.'"},
   {q:"Mia hat den See besonders gemocht.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Am liebsten mochte ich den großen See.'"},
   {q:"Nächstes Jahr will die Familie im Winter fahren.",options:["Richtig","Falsch"],answer:"Falsch",explain:"Sie will wieder fahren, 'aber im Sommer'."}]},
 {type:"lesen",title:"Lesen · Teil 2",instr:"Welche Anzeige (A–F) passt zu welcher Person? Eine Anzeige bleibt übrig.",
  ads:[{k:"A",t:"Deutschkurse am Abend — kleine Gruppen, alle Niveaus. Zentrale Lage, faire Preise."},
   {k:"B",t:"Gebrauchtes Fahrrad zu verkaufen, guter Zustand, 80 €. Nur Abholung."},
   {k:"C",t:"Suchst du eine WG? Schönes Zimmer (18 m²) in ruhiger Lage, ab sofort frei, 350 € warm."},
   {k:"D",t:"Hundebetreuung! Ich gehe mit deinem Hund spazieren, wenn du arbeitest. Zuverlässig und tierlieb."},
   {k:"E",t:"Yoga im Park — jeden Sonntag um 9 Uhr, kostenlos. Einfach vorbeikommen, Matte mitbringen!"},
   {k:"F",t:"Nachhilfe in Mathe für Schüler, Klasse 5–10. Auch online möglich. Erste Stunde gratis."}],
  items:[
   {q:"Herr Klein möchte am Wochenende kostenlos Sport machen.",options:["A","B","C","D","E","F"],answer:"E",explain:"E: Yoga im Park, sonntags, kostenlos."},
   {q:"Lena sucht ein günstiges Zimmer zum Wohnen.",options:["A","B","C","D","E","F"],answer:"C",explain:"C: WG-Zimmer, 350 € warm."},
   {q:"Tom braucht am Abend einen Deutschkurs.",options:["A","B","C","D","E","F"],answer:"A",explain:"A: Deutschkurse am Abend."},
   {q:"Frau Bauer sucht jemanden, der mit ihrem Hund geht.",options:["A","B","C","D","E","F"],answer:"D",explain:"D: Hundebetreuung."},
   {q:"Paul braucht Hilfe in Mathematik.",options:["A","B","C","D","E","F"],answer:"F",explain:"F: Nachhilfe in Mathe."}]},
 {type:"hoeren",title:"Hören · Teil 1",instr:"Hören Sie vier kurze Ansagen. Sind die Aussagen *richtig* oder *falsch*?",
  script:"Ansage eins. Achtung, ein Hinweis für alle Reisenden: Der Zug nach Hamburg um vierzehn Uhr zwanzig fällt heute leider aus. Bitte nehmen Sie den nächsten Zug um fünfzehn Uhr. ... Ansage zwei. Hallo Markus, hier ist Lisa. Können wir unser Treffen auf morgen verschieben? Heute muss ich leider länger arbeiten. Ruf mich bitte zurück. ... Ansage drei. Liebe Kundinnen und Kunden, unser Supermarkt schließt heute schon um achtzehn Uhr, weil wir Inventur machen. Morgen sind wir wieder normal für Sie da. ... Ansage vier. Guten Morgen! Heute wird es sonnig und warm, bis zu sechsundzwanzig Grad. Am Abend kann es aber ein Gewitter geben. Denken Sie an einen Schirm.",
  items:[
   {q:"Ansage 1: Der Zug nach Hamburg fährt pünktlich um 14:20 Uhr.",options:["Richtig","Falsch"],answer:"Falsch",explain:"Der Zug 'fällt heute leider aus'."},
   {q:"Ansage 2: Lisa möchte das Treffen verschieben.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Können wir unser Treffen auf morgen verschieben?'"},
   {q:"Ansage 3: Der Supermarkt schließt heute früher als sonst.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'schließt heute schon um achtzehn Uhr, weil wir Inventur machen'."},
   {q:"Ansage 4: Am Abend soll das Wetter schlecht werden.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Am Abend kann es aber ein Gewitter geben.'"}],
  transcript:"Ansage 1: Der Zug nach Hamburg (14:20) fällt aus, nächster Zug 15:00.\nAnsage 2: Lisa will das Treffen auf morgen verschieben.\nAnsage 3: Der Supermarkt schließt heute um 18 Uhr (Inventur).\nAnsage 4: Sonnig, bis 26 Grad, am Abend Gewitter möglich."},
 {type:"hoeren",title:"Hören · Teil 2",instr:"Hören Sie das Interview. Wählen Sie die richtige Antwort.",
  script:"Moderatorin: Heute spreche ich mit Herrn Wagner über sein Hobby. Herr Wagner, was machen Sie in Ihrer Freizeit? ... Herr Wagner: Ich fotografiere sehr gern, am liebsten die Natur. Jedes Wochenende fahre ich mit dem Fahrrad raus und mache Fotos von Tieren und Landschaften. ... Moderatorin: Und wie lange machen Sie das schon? ... Herr Wagner: Seit ungefähr zehn Jahren. Angefangen habe ich, als mir mein Vater seine alte Kamera geschenkt hat. ... Moderatorin: Ist Fotografieren teuer? ... Herr Wagner: Am Anfang nicht, aber gute Objektive kosten leider viel Geld. Trotzdem lohnt es sich für mich. ... Moderatorin: Haben Sie einen Tipp für Anfänger? ... Herr Wagner: Ja, einfach viel üben und Geduld haben. Die besten Fotos entstehen oft, wenn man wartet.",
  items:[
   {q:"Was ist das Hobby von Herrn Wagner?",options:["Fotografieren","Radrennen","Angeln"],answer:"Fotografieren",explain:"'Ich fotografiere sehr gern, am liebsten die Natur.'"},
   {q:"Wann macht er meistens Fotos?",options:["jeden Abend","jedes Wochenende","einmal im Monat"],answer:"jedes Wochenende",explain:"'Jedes Wochenende fahre ich mit dem Fahrrad raus.'"},
   {q:"Wie hat er mit dem Hobby angefangen?",options:["mit einem Kurs","mit der Kamera seines Vaters","in der Schule"],answer:"mit der Kamera seines Vaters",explain:"'als mir mein Vater seine alte Kamera geschenkt hat'."},
   {q:"Welchen Tipp gibt er Anfängern?",options:["teure Objektive kaufen","viel üben und geduldig sein","früh aufstehen"],answer:"viel üben und geduldig sein",explain:"'einfach viel üben und Geduld haben'."}],
  transcript:"Herr Wagner fotografiert gern die Natur, jedes Wochenende mit dem Fahrrad. Er macht das seit ~10 Jahren; angefangen mit der alten Kamera seines Vaters. Gute Objektive sind teuer. Tipp: viel üben und Geduld haben."},
 {type:"schreiben",title:"Schreiben · Aufgabe 1",instr:"Schreiben Sie eine informelle E-Mail (ca. 80 Wörter). Schreiben Sie zu allen drei Punkten.",
  situation:"Deine Freundin Nadia hat dir geschrieben, dass sie nächsten Monat in deine Stadt zieht. Antworte ihr.",
  points:["Freue dich über die Nachricht.","Beschreibe deine Stadt kurz.","Mach einen Vorschlag, was ihr zusammen machen könnt."],minWords:80,
  model:"Liebe Nadia,\n\nvielen Dank für deine Nachricht — ich habe mich riesig gefreut, dass du in meine Stadt ziehst! Das ist eine tolle Neuigkeit.\n\nMeine Stadt ist nicht sehr groß, aber sehr gemütlich. Es gibt viele Cafés, einen schönen Park und ein kleines Kino. Am Wochenende ist im Zentrum immer etwas los.\n\nWenn du angekommen bist, könnten wir zusammen die Stadt anschauen und danach einen Kaffee trinken. Vielleicht am ersten Samstag?\n\nSchreib mir, wann du kommst. Ich freue mich schon sehr!\n\nLiebe Grüße,\n[Dein Name]"},
 {type:"sprechen",title:"Sprechen · Teil 2",instr:"Präsentieren Sie ein Thema (ca. 2–3 Minuten). Hören Sie die Musterantwort zur Orientierung.",
  prompt:"Präsentiere das Thema „Warum es wichtig ist, Fremdsprachen zu lernen“.",
  structure:["Einleitung: Nenne das Thema und deine Meinung.","Deine Erfahrung: Welche Sprachen lernst oder sprichst du?","Vorteile & Schwierigkeiten: Warum ist es nützlich?","Situation in deinem Land: Lernen viele Menschen Sprachen?","Abschluss: Fasse zusammen und bedanke dich."],
  model:"Ich möchte über das Thema „Fremdsprachen lernen“ sprechen. Meiner Meinung nach ist das sehr wichtig. Ich selbst lerne gerade Deutsch und spreche außerdem Englisch. Fremdsprachen haben viele Vorteile: Man kann im Ausland reisen, neue Freunde finden und hat bessere Chancen im Beruf. Natürlich ist es manchmal schwierig, besonders die Grammatik braucht viel Geduld. In meinem Land lernen die meisten Menschen in der Schule Englisch, aber immer mehr interessieren sich auch für andere Sprachen. Zusammenfassend finde ich: Sprachen öffnen Türen. Deshalb lohnt sich die Mühe auf jeden Fall. Vielen Dank fürs Zuhören."}
]});
exam({id:"m2",title:"B1 Modelltest 2",sub:"Zweiter kompletter Test mit neuen Texten, Hörtexten und Aufgaben.",sections:[
 {type:"lesen",title:"Lesen · Teil 1",instr:"Lesen Sie den Text. Sind die Aussagen *richtig* oder *falsch*?",
  text:"*Vom Büro in die Küche*\n\nJulia Berger hat lange in einer großen Firma als Ingenieurin gearbeitet. Sie hatte ein gutes Gehalt, aber sie war nicht glücklich. „Ich saß den ganzen Tag am Computer und hatte kaum Zeit für meine Familie“, erzählt sie. Vor zwei Jahren hat Julia eine mutige Entscheidung getroffen: Sie kündigte ihren Job und eröffnete ein kleines Café. Am Anfang war es sehr schwer, denn sie musste viel lernen und arbeitete oft zwölf Stunden am Tag. Heute läuft das Café gut und Julia ist zufrieden. „Ich verdiene weniger als früher, aber ich bin viel glücklicher“, sagt sie. Ihr Tipp: „Man sollte keine Angst vor Veränderungen haben.“",
  items:[
   {q:"Julia war mit ihrer Arbeit als Ingenieurin zufrieden.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'sie war nicht glücklich'."},
   {q:"Sie hat ihren Job gekündigt und ein Café eröffnet.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Sie kündigte ihren Job und eröffnete ein kleines Café.'"},
   {q:"Am Anfang war die neue Arbeit leicht.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Am Anfang war es sehr schwer.'"},
   {q:"Heute verdient Julia mehr Geld als früher.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Ich verdiene weniger als früher.'"},
   {q:"Julia rät, keine Angst vor Veränderungen zu haben.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Man sollte keine Angst vor Veränderungen haben.'"}]},
 {type:"lesen",title:"Lesen · Teil 2",instr:"Welche Anzeige (A–F) passt zu welcher Person? Eine bleibt übrig.",
  ads:[{k:"A",t:"Kochkurs für Anfänger: italienische Küche. Jeden Dienstag, 19 Uhr. Zutaten inklusive."},
   {k:"B",t:"Gitarrenunterricht für Kinder und Erwachsene. Erste Probestunde kostenlos!"},
   {k:"C",t:"Wir suchen ehrenamtliche Helfer für unser Tierheim am Wochenende. Melde dich!"},
   {k:"D",t:"Fitnessstudio neu eröffnet — im ersten Monat nur 10 €. Sauna und Kurse inklusive."},
   {k:"E",t:"Flohmarkt am Samstag auf dem Marktplatz. Kaufen, verkaufen, stöbern von 8 bis 14 Uhr."},
   {k:"F",t:"Reisegruppe sucht Mitfahrer nach München am Freitag. Wir teilen die Kosten."}],
  items:[
   {q:"Anna möchte ein Instrument lernen.",options:["A","B","C","D","E","F"],answer:"B",explain:"B: Gitarrenunterricht."},
   {q:"Herr Ott will günstig Sport machen.",options:["A","B","C","D","E","F"],answer:"D",explain:"D: Fitnessstudio, erster Monat nur 10 €."},
   {q:"Maria möchte am Wochenende Tieren helfen.",options:["A","B","C","D","E","F"],answer:"C",explain:"C: Helfer fürs Tierheim am Wochenende."},
   {q:"Eine Familie sucht alte, billige Sachen.",options:["A","B","C","D","E","F"],answer:"E",explain:"E: Flohmarkt."},
   {q:"David will am Freitag günstig nach München reisen.",options:["A","B","C","D","E","F"],answer:"F",explain:"F: Mitfahrer nach München, Kosten teilen."}]},
 {type:"hoeren",title:"Hören · Teil 1",instr:"Hören Sie vier kurze Ansagen. *Richtig* oder *falsch*?",
  script:"Ansage eins. Willkommen im Museum. Bitte beachten Sie: Das Fotografieren ist im ganzen Gebäude verboten. Vielen Dank für Ihr Verständnis. ... Ansage zwei. Hallo Papa, ich bin es, Jonas. Der Bus hatte Verspätung, ich komme erst um sieben Uhr nach Hause. Fang schon mal ohne mich mit dem Essen an. ... Ansage drei. Liebe Fahrgäste, wegen Bauarbeiten fährt die Straßenbahn Linie drei heute nicht. Bitte benutzen Sie den Ersatzbus vor dem Bahnhof. ... Ansage vier. Nächste Woche startet unser Sommerschlussverkauf. Auf viele Schuhe und Jacken gibt es bis zu fünfzig Prozent Rabatt. Kommen Sie vorbei!",
  items:[
   {q:"Ansage 1: Im Museum darf man fotografieren.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Das Fotografieren ist im ganzen Gebäude verboten.'"},
   {q:"Ansage 2: Jonas kommt später nach Hause als geplant.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Der Bus hatte Verspätung, ich komme erst um sieben Uhr.'"},
   {q:"Ansage 3: Die Straßenbahn Linie 3 fährt heute normal.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'fährt die Straßenbahn Linie drei heute nicht'."},
   {q:"Ansage 4: Nächste Woche gibt es reduzierte Preise.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Sommerschlussverkauf … bis zu fünfzig Prozent Rabatt'."}],
  transcript:"1: Fotografieren im Museum verboten.\n2: Jonas kommt erst um 19 Uhr (Bus-Verspätung).\n3: Straßenbahn Linie 3 fährt heute nicht (Bauarbeiten), Ersatzbus.\n4: Nächste Woche Sommerschlussverkauf, bis 50 % Rabatt."},
 {type:"hoeren",title:"Hören · Teil 2",instr:"Hören Sie das Gespräch. Wählen Sie die richtige Antwort.",
  script:"Anna: Du, Ben, Lauras Geburtstag ist nächste Woche. Sollen wir zusammen etwas organisieren? ... Ben: Gute Idee! Was schlägst du vor? Ein Essen im Restaurant? ... Anna: Hm, letztes Jahr waren wir schon essen. Vielleicht machen wir dieses Mal ein Picknick im Park? ... Ben: Das gefällt mir! Bei gutem Wetter ist das perfekt. Aber was, wenn es regnet? ... Anna: Dann treffen wir uns einfach bei mir zu Hause. Ich habe genug Platz. ... Ben: Super. Ich kümmere mich um den Kuchen und die Getränke. Kannst du die anderen Freunde einladen? ... Anna: Klar, das mache ich heute Abend. Und ein Geschenk? Laura wünscht sich ein Buch. ... Ben: Perfekt, dann kaufen wir zusammen eins.",
  items:[
   {q:"Was wollen Anna und Ben organisieren?",options:["eine Reise","eine Geburtstagsfeier","ein Konzert"],answer:"eine Geburtstagsfeier",explain:"'Lauras Geburtstag ist nächste Woche.'"},
   {q:"Was möchten sie dieses Jahr machen?",options:["ins Restaurant gehen","ein Picknick im Park","ins Kino gehen"],answer:"ein Picknick im Park",explain:"'Vielleicht machen wir dieses Mal ein Picknick im Park?'"},
   {q:"Was machen sie, wenn es regnet?",options:["Sie feiern bei Anna zu Hause.","Sie verschieben die Feier.","Sie gehen ins Restaurant."],answer:"Sie feiern bei Anna zu Hause.",explain:"'Dann treffen wir uns einfach bei mir zu Hause.'"},
   {q:"Was wünscht sich Laura?",options:["ein Buch","Blumen","eine Tasche"],answer:"ein Buch",explain:"'Laura wünscht sich ein Buch.'"}],
  transcript:"Anna und Ben planen Lauras Geburtstag: ein Picknick im Park, bei Regen bei Anna zu Hause. Ben bringt Kuchen und Getränke, Anna lädt die Freunde ein. Geschenk: ein Buch."},
 {type:"schreiben",title:"Schreiben · Aufgabe 1",instr:"Schreiben Sie eine informelle E-Mail (ca. 80 Wörter). Alle drei Punkte behandeln.",
  situation:"Du hast eine wichtige Prüfung bestanden und möchtest das feiern. Schreibe eine E-Mail an deinen Freund Ben.",
  points:["Erzähle, welche Prüfung du bestanden hast.","Lade Ben zu einer Feier ein (wann und wo).","Bitte ihn, etwas mitzubringen."],minWords:80,
  model:"Lieber Ben,\n\nich habe tolle Neuigkeiten: Ich habe meine Deutschprüfung bestanden! Ich freue mich riesig, denn ich habe lange dafür gelernt.\n\nDas möchte ich natürlich feiern und lade dich herzlich ein. Die Feier ist am Samstag um 19 Uhr bei mir zu Hause. Es kommen noch ein paar andere Freunde.\n\nKönntest du vielleicht etwas zu trinken mitbringen? Um das Essen kümmere ich mich.\n\nSag mir bitte bis Donnerstag Bescheid, ob du kommen kannst. Ich freue mich auf dich!\n\nLiebe Grüße,\n[Dein Name]"},
 {type:"sprechen",title:"Sprechen · Teil 1",instr:"Etwas gemeinsam planen. Hören Sie die Musterantwort als Beispiel.",
  prompt:"Plant gemeinsam einen Ausflug für eure Deutschklasse. Sprecht über: Wohin? Wann? Wie kommt ihr dorthin? Was nehmt ihr mit?",
  structure:["Mach einen Vorschlag: „Sollen wir …?“ / „Wie wäre es mit …?“","Reagiere: zustimmen oder ablehnen *mit Alternative*.","Klärt die Details: Zeit, Ort, Transport, was mitbringen.","Trefft eine gemeinsame Entscheidung."],
  model:"Sollen wir mit der Klasse einen Ausflug an den See machen? – Gute Idee! Wann passt es dir? – Wie wäre es mit dem nächsten Samstag? – Samstag ist super. Wie kommen wir dorthin? – Ich schlage vor, wir fahren mit dem Zug, das ist günstig und einfach. – Einverstanden. Und was nehmen wir mit? – Jeder bringt etwas zu essen mit, und ich kümmere mich um die Getränke. – Perfekt, dann treffen wir uns um neun Uhr am Bahnhof. Abgemacht!"}
]});
exam({id:"m3",title:"B1 Modelltest 3",sub:"Dritter Test — mit einem Meinungstext im Schreiben (Forum).",sections:[
 {type:"lesen",title:"Lesen · Teil 1",instr:"Lesen Sie den Text. Sind die Aussagen *richtig* oder *falsch*?",
  text:"*Ein Jahr im Ausland*\n\nNach der Schule wusste Tim nicht genau, was er studieren wollte. Deshalb entschied er sich, erst einmal ein Jahr ins Ausland zu gehen. Er arbeitete als Freiwilliger in einer Schule in Spanien und half den Kindern beim Lernen. Am Anfang war die Sprache ein großes Problem, denn Tim sprach kaum Spanisch. Doch nach ein paar Monaten konnte er sich schon gut unterhalten. „Diese Zeit hat mich sehr verändert“, sagt Tim heute. „Ich bin selbstständiger geworden und habe viele nette Leute kennengelernt.“ Jetzt studiert Tim Lehramt, weil ihm die Arbeit mit Kindern so viel Spaß gemacht hat. Das Auslandsjahr bereut er kein bisschen.",
  items:[
   {q:"Tim wusste nach der Schule sofort, was er studieren will.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'wusste Tim nicht genau, was er studieren wollte'."},
   {q:"Er hat im Ausland in einer Schule geholfen.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'arbeitete als Freiwilliger in einer Schule … half den Kindern'."},
   {q:"Tim konnte von Anfang an gut Spanisch.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Am Anfang war die Sprache ein großes Problem … sprach kaum Spanisch'."},
   {q:"Das Jahr im Ausland hat ihn verändert.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Diese Zeit hat mich sehr verändert.'"},
   {q:"Tim bereut das Auslandsjahr.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Das Auslandsjahr bereut er kein bisschen.'"}]},
 {type:"lesen",title:"Lesen · Teil 2",instr:"Welcher Aushang (A–F) passt zu welcher Person? Einer bleibt übrig.",
  ads:[{k:"A",t:"Umzugshelfer gesucht! Samstag, ein paar Stunden. Bezahlung und Pizza inklusive."},
   {k:"B",t:"Biete Nachhilfe in Englisch und Französisch, alle Klassen. Flexible Zeiten."},
   {k:"C",t:"Kinderwagen zu verschenken, guter Zustand. Nur Abholung im 2. Stock."},
   {k:"D",t:"Neuer Waschmaschinen-Raum im Keller ab Montag. Bitte Zeiten in die Liste eintragen."},
   {k:"E",t:"Tauschbörse für Bücher im Gemeinschaftsraum. Bring ein Buch, nimm ein Buch mit!"},
   {k:"F",t:"Gartenfest am Sonntag für alle Nachbarn. Bitte Salate oder Kuchen mitbringen."}],
  items:[
   {q:"Frau Sanchez sucht kostenlose Bücher zum Lesen.",options:["A","B","C","D","E","F"],answer:"E",explain:"E: Bücher-Tauschbörse."},
   {q:"Herr Yilmaz möchte am Samstag etwas Geld verdienen und helfen.",options:["A","B","C","D","E","F"],answer:"A",explain:"A: Umzugshelfer gesucht, mit Bezahlung."},
   {q:"Eine Familie braucht einen Kinderwagen und hat wenig Geld.",options:["A","B","C","D","E","F"],answer:"C",explain:"C: Kinderwagen zu verschenken (gratis)."},
   {q:"Sofia möchte am Sonntag ihre Nachbarn treffen.",options:["A","B","C","D","E","F"],answer:"F",explain:"F: Gartenfest am Sonntag für alle Nachbarn."},
   {q:"Ein Schüler braucht Hilfe in Französisch.",options:["A","B","C","D","E","F"],answer:"B",explain:"B: Nachhilfe in Englisch und Französisch."}]},
 {type:"hoeren",title:"Hören · Teil 1",instr:"Hören Sie vier kurze Ansagen. *Richtig* oder *falsch*?",
  script:"Ansage eins. Sehr geehrte Fahrgäste, der Zug nach Frankfurt hat heute etwa zehn Minuten Verspätung. Wir bitten um Ihr Verständnis. ... Ansage zwei. Hallo Sarah, hier ist Oma. Vielen Dank für die schönen Blumen zum Geburtstag! Ruf mich an, wenn du Zeit hast. ... Ansage drei. Achtung, eine Durchsage für alle Schüler: Der Deutschunterricht in der dritten Stunde fällt heute aus. Herr Klein ist krank. Bitte geht in die Bibliothek. ... Ansage vier. Guten Tag, hier ist die Praxis Doktor Schmidt. Ihr Termin am Mittwoch muss leider verschoben werden. Bitte rufen Sie uns für einen neuen Termin an.",
  items:[
   {q:"Ansage 1: Der Zug nach Frankfurt ist pünktlich.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'hat heute etwa zehn Minuten Verspätung'."},
   {q:"Ansage 2: Die Oma bedankt sich für ein Geschenk.",options:["Richtig","Falsch"],answer:"Richtig",explain:"'Vielen Dank für die schönen Blumen zum Geburtstag!'"},
   {q:"Ansage 3: Der Deutschunterricht findet heute normal statt.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Der Deutschunterricht … fällt heute aus.'"},
   {q:"Ansage 4: Der Arzttermin am Mittwoch bleibt gleich.",options:["Richtig","Falsch"],answer:"Falsch",explain:"'Ihr Termin am Mittwoch muss leider verschoben werden.'"}],
  transcript:"1: Zug nach Frankfurt ~10 Min. Verspätung.\n2: Oma bedankt sich für die Geburtstagsblumen.\n3: Deutschunterricht (3. Stunde) fällt aus, Herr Klein krank → Bibliothek.\n4: Arzttermin am Mittwoch wird verschoben, bitte anrufen."},
 {type:"hoeren",title:"Hören · Teil 2",instr:"Hören Sie das Gespräch bei einer Wohnungsbesichtigung. Wählen Sie die richtige Antwort.",
  script:"Vermieterin: Guten Tag, schön, dass Sie da sind. Das ist also die Wohnung. Wie Sie sehen, ist sie hell und ruhig. ... Interessent: Ja, sie gefällt mir gut. Wie groß ist sie denn genau? ... Vermieterin: Sie hat sechzig Quadratmeter, mit zwei Zimmern, Küche und Bad. Und es gibt einen kleinen Balkon. ... Interessent: Sehr schön. Und was kostet die Wohnung? ... Vermieterin: Die Miete beträgt siebenhundert Euro warm, also mit Heizung und Wasser. ... Interessent: Das ist in Ordnung. Ist ein Supermarkt in der Nähe? ... Vermieterin: Ja, gleich um die Ecke. Auch eine Bushaltestelle ist nur zwei Minuten entfernt. ... Interessent: Perfekt. Kann ich es mir bis morgen überlegen? ... Vermieterin: Natürlich. Rufen Sie mich einfach an.",
  items:[
   {q:"Wie viele Zimmer hat die Wohnung?",options:["ein Zimmer","zwei Zimmer","drei Zimmer"],answer:"zwei Zimmer",explain:"'mit zwei Zimmern, Küche und Bad'."},
   {q:"Was gehört zur Wohnung?",options:["ein Garten","ein Balkon","eine Garage"],answer:"ein Balkon",explain:"'Und es gibt einen kleinen Balkon.'"},
   {q:"Wie viel kostet die Wohnung?",options:["600 Euro","700 Euro","800 Euro"],answer:"700 Euro",explain:"'Die Miete beträgt siebenhundert Euro warm.'"},
   {q:"Was ist in der Nähe?",options:["ein Supermarkt und eine Bushaltestelle","nur ein Bahnhof","eine Schule"],answer:"ein Supermarkt und eine Bushaltestelle",explain:"'ein Supermarkt … gleich um die Ecke. Auch eine Bushaltestelle … zwei Minuten entfernt.'"}],
  transcript:"Wohnung: hell, ruhig, 60 m², 2 Zimmer + Küche + Bad, kleiner Balkon. Miete 700 € warm. In der Nähe: Supermarkt (um die Ecke) und Bushaltestelle (2 Min.). Interessent überlegt es sich bis morgen."},
 {type:"schreiben",title:"Schreiben · Aufgabe 2 (Forum)",instr:"Schreiben Sie Ihre Meinung in ein Internetforum (ca. 80 Wörter). Behandeln Sie alle Punkte.",
  situation:"In einem Internetforum lesen Sie die Frage: „Sollten Handys in der Schule verboten werden?“ Schreiben Sie Ihre Meinung.",
  points:["Nenne deine Meinung zum Thema.","Gib einen Grund oder ein Beispiel.","Nenne einen Vorteil oder Nachteil von Handys in der Schule."],minWords:80,
  model:"Ich finde die Frage sehr interessant. Meiner Meinung nach sollten Handys im Unterricht nicht komplett verboten werden.\n\nNatürlich können Handys stören, wenn die Schüler damit spielen oder Nachrichten schreiben, statt aufzupassen. Das ist ein klarer Nachteil.\n\nAuf der anderen Seite kann man mit dem Handy auch gut lernen, zum Beispiel Wörter nachschlagen oder Informationen suchen. In meiner Schule haben wir manchmal Apps benutzt, und das hat gut funktioniert.\n\nDeshalb denke ich: Handys sollten erlaubt sein, aber nur, wenn der Lehrer es sagt."},
 {type:"sprechen",title:"Sprechen · Teil 2",instr:"Präsentieren Sie ein Thema (ca. 2–3 Minuten). Hören Sie die Musterantwort zur Orientierung.",
  prompt:"Präsentiere das Thema „Gesund leben“.",
  structure:["Einleitung: Nenne das Thema und was es für dich bedeutet.","Deine Erfahrung: Wie lebst du?","Vorteile: Warum ist gesund leben wichtig?","In deinem Land: Wie ist die Situation?","Abschluss: Zusammenfassung und Dank."],
  model:"Ich spreche heute über das Thema „Gesund leben“. Für mich bedeutet das vor allem, sich richtig zu ernähren und sich zu bewegen. Ich selbst versuche, viel Obst und Gemüse zu essen und dreimal pro Woche Sport zu machen. Gesund zu leben hat viele Vorteile: Man fühlt sich fitter, ist seltener krank und hat mehr Energie. In meinem Land achten immer mehr Menschen auf ihre Gesundheit, zum Beispiel gehen viele joggen. Manche haben aber wenig Zeit und essen oft Fast Food. Zusammenfassend denke ich, dass ein gesundes Leben sehr wichtig ist. Vielen Dank fürs Zuhören."}
]});
//__EXAMS__
